apiVersion: v2
name: frigate
version: 0.2.4
appVersion: 0.16.2
dependencies:
- name: frigate
  repository: https://blakeblackshear.github.io/blakeshome-charts/
  version: 7.8.0
- name: app-template
  version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts
