apiVersion: v2
name: monitoring
description: A Helm chart for Grafana monitoring
version: 0.1.1
dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.2.0
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 27.47.0
